[build]
  base = "client/dist"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "client/netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200